# Generated by Django 5.1.4 on 2024-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adresse',
            field=models.EmailField(max_length=254),
        ),
    ]
