# Generated by Django 5.1.4 on 2024-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0003_employee_email_employee_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
