# Generated by Django 5.1.4 on 2024-12-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0004_alter_employee_email_alter_employee_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_rh.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
