# Generated by Django 5.1.4 on 2024-12-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0005_employe_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_emp', to='admin_rh.service'),
        ),
    ]
