# Generated by Django 5.1.4 on 2024-12-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0006_alter_employe_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Absence', models.DateField()),
                ('Reason', models.CharField(max_length=500)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_abs', to='admin_rh.employe')),
            ],
        ),
    ]
