# Generated by Django 5.1.4 on 2024-12-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0007_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massrouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_avance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('justification', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_rh.employe')),
            ],
        ),
        migrations.DeleteModel(
            name='Salaire',
        ),
    ]
