# Generated by Django 5.1.4 on 2024-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0008_massrouf_delete_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'HOMME'), ('F', 'FEMME')], default='M', max_length=10),
        ),
    ]
