# Generated by Django 5.1.4 on 2024-12-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0009_employe_sexe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Évaluation',
        ),
    ]
