# Generated by Django 5.1.4 on 2024-12-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0010_delete_évaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='Date_Absence',
            new_name='date_Absence',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='Reason',
            new_name='justification',
        ),
    ]
