# Generated by Django 5.1.4 on 2025-01-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0012_pointage_delete_candidat_remove_contrat_salaire_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='salaireJrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaireMois', models.FloatField()),
                ('moisdetravail', models.IntegerField()),
                ('mois', models.CharField(max_length=10)),
                ('annee', models.IntegerField(default=2025)),
                ('Salaire_jr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_rh.contrat')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sal_emp', to='admin_rh.employe')),
            ],
        ),
    ]
