# Generated by Django 5.1.5 on 2025-01-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0013_contrat_salairejrs_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='congé',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conge_emp', to='admin_rh.employe'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_rh.employe'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='Salaire_jr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_rh.contrat'),
        ),
        migrations.DeleteModel(
            name='Pointage',
        ),
    ]
