# Generated by Django 5.1.5 on 2025-01-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0014_congé_employe_alter_contrat_employe_and_more'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='évaluation',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_employe', to='admin_rh.employe'),
        ),
        migrations.AddField(
            model_name='évaluation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_manager', to='admin_rh.employe'),
        ),
    ]
