# Generated by Django 5.1.4 on 2024-12-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rh', '0011_rename_date_absence_absence_date_absence_and_more'),
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='recrutement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='admin_rh.recrutement'),
        ),
    ]
